export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const USER_INIT = 'USER_INIT'
export const USER_INIT_SUCCESS = 'USER_INIT_SUCCESS'
export const USER_INIT_FAILED = 'USER_INIT_FAILED'

export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED'
export const CALL_REFRESH_TOKEN = 'CALL_REFRESH_TOKEN'

// CHALLENGE
export const FIND_ALL_CHALLENGE = 'FIND_ALL_CHALLENGE'
export const FIND_ALL_CHALLENGE_SUCCESS = 'FIND_ALL_CHALLENGE_SUCCESS'
export const FIND_ALL_CHALLENGE_FAILED = 'FIND_ALL_CHALLENGE_FAILED'

export const FIND_CHALLENGE_BY_ID = 'FIND_CHALLENGE_BY_ID'
export const FIND_CHALLENGE_BY_ID_SUCCESS = 'FIND_CHALLENGE_BY_ID_SUCCESS'
export const FIND_CHALLENGE_BY_ID_FAILED = 'FIND_CHALLENGE_BY_ID_FAILED'

export const FIND_CHALLENGE_BY_CONDITION = 'FIND_CHALLENGE_BY_CONDITION'
export const FIND_CHALLENGE_BY_CONDITION_SUCCESS = 'FIND_CHALLENGE_BY_CONDITION_SUCCESS'
export const FIND_CHALLENGE_BY_CONDITION_FAILED = 'FIND_CHALLENGE_BY_CONDITION_FAILED'

export const CREATE_CHALLENGE = 'SAVE_CHALLENGE'
export const CREATE_CHALLENGE_SUCCESS = 'SAVE_CHALLENGE_SUCCESS'
export const CREATE_CHALLENGE_FAILED = 'SAVE_CHALLENGE_FAILED'

export const UPDATE_CHALLENGE = 'UPDATE_CHALLENGE'
export const UPDATE_CHALLENGE_SUCCESS = 'UPDATE_CHALLENGE_SUCCESS'
export const UPDATE_CHALLENGE_FAILED = 'UPDATE_CHALLENGE_FAILED'

export const SAVE_DRAFT_CHALLENGE = 'SAVE_DRAFT_CHALLENGE'
export const SAVE_DRAFT_CHALLENGE_SUCCESS = 'SAVE_DRAFT_CHALLENGE_SUCCESS'
export const SAVE_DRAFT_CHALLENGE_FAILED = 'SAVE_DRAFT_CHALLENGE_FAILED'

export const UPDATE_DRAFT_CHALLENGE = 'UPDATE_DRAFT_CHALLENGE'
export const UPDATE_DRAFT_CHALLENGE_SUCCESS = 'UPDATE_DRAFT_CHALLENGE_SUCCESS'
export const UPDATE_DRAFT_CHALLENGE_FAILED = 'UPDATE_DRAFT_CHALLENGE_FAILED'

export const DELETE_CHALLENGE = 'DELETE_CHALLENGE'
export const DELETE_CHALLENGE_SUCCESS = 'DELETE_CHALLENGE_SUCCESS'
export const DELETE_CHALLENGE_FAILED = 'DELETE_CHALLENGE_FAILED'

export const ACTIVE_CHALLENGE = 'ACTIVE_CHALLENGE'
export const ACTIVE_CHALLENGE_SUCCESS = 'ACTIVE_CHALLENGE_SUCCESS'
export const ACTIVE_CHALLENGE_FAILED = 'ACTIVE_CHALLENGE_FAILED'

export const INACTIVE_CHALLENGE = 'INACTIVE_CHALLENGE'
export const INACTIVE_CHALLENGE_SUCCESS = 'INACTIVE_CHALLENGE_SUCCESS'
export const INACTIVE_CHALLENGE_FAILED = 'INACTIVE_CHALLENGE_FAILED'

// CONTEST
export const FIND_ALL_CONTEST = 'FIND_ALL_CONTEST'
export const FIND_ALL_CONTEST_SUCCESS = 'FIND_ALL_CONTEST_SUCCESS'
export const FIND_ALL_CONTEST_FAILED = 'FIND_ALL_CONTEST_FAILED'

export const FIND_CONTEST_BY_ID = 'FIND_CONTEST_BY_ID'
export const FIND_CONTEST_BY_ID_SUCCESS = 'FIND_CONTEST_BY_ID_SUCCESS'
export const FIND_CONTEST_BY_ID_FAILED = 'FIND_CONTEST_BY_ID_FAILED'

export const FIND_CONTEST_BY_CONDITION = 'FIND_CONTEST_BY_CONDITION'
export const FIND_CONTEST_BY_CONDITION_SUCCESS = 'FIND_CONTEST_BY_CONDITION_SUCCESS'
export const FIND_CONTEST_BY_CONDITION_FAILED = 'FIND_CONTEST_BY_CONDITION_FAILED'

export const CREATE_CONTEST = 'SAVE_CONTEST'
export const CREATE_CONTEST_SUCCESS = 'SAVE_CONTEST_SUCCESS'
export const CREATE_CONTEST_FAILED = 'SAVE_CONTEST_FAILED'

export const UPDATE_CONTEST = 'UPDATE_CONTEST'
export const UPDATE_CONTEST_SUCCESS = 'UPDATE_CONTEST_SUCCESS'
export const UPDATE_CONTEST_FAILED = 'UPDATE_CONTEST_FAILED'

export const SAVE_DRAFT_CONTEST = 'SAVE_DRAFT_CONTEST'
export const SAVE_DRAFT_CONTEST_SUCCESS = 'SAVE_DRAFT_CONTEST_SUCCESS'
export const SAVE_DRAFT_CONTEST_FAILED = 'SAVE_DRAFT_CONTEST_FAILED'

export const UPDATE_DRAFT_CONTEST = 'UPDATE_DRAFT_CONTEST'
export const UPDATE_DRAFT_CONTEST_SUCCESS = 'UPDATE_DRAFT_CONTEST_SUCCESS'
export const UPDATE_DRAFT_CONTEST_FAILED = 'UPDATE_DRAFT_CONTEST_FAILED'

export const DELETE_CONTEST = 'DELETE_CONTEST'
export const DELETE_CONTEST_SUCCESS = 'DELETE_CONTEST_SUCCESS'
export const DELETE_CONTEST_FAILED = 'DELETE_CONTEST_FAILED'

export const ACTIVE_CONTEST = 'ACTIVE_CONTEST'
export const ACTIVE_CONTEST_SUCCESS = 'ACTIVE_CONTEST_SUCCESS'
export const ACTIVE_CONTEST_FAILED = 'ACTIVE_CONTEST_FAILED'

export const INACTIVE_CONTEST = 'INACTIVE_CONTEST'
export const INACTIVE_CONTEST_SUCCESS = 'INACTIVE_CONTEST_SUCCESS'
export const INACTIVE_CONTEST_FAILED = 'INACTIVE_CONTEST_FAILED'

// BADGE
export const FIND_ALL_BADGE = 'FIND_ALL_BADGE'
export const FIND_ALL_BADGE_SUCCESS = 'FIND_ALL_BADGE_SUCCESS'
export const FIND_ALL_BADGE_FAILED = 'FIND_ALL_BADGE_FAILED'

export const FIND_ALL_ASSOCIATED_BADGE = 'FIND_ALL_ASSOCIATED_BADGE'
export const FIND_ALL_ASSOCIATED_BADGE_SUCCESS = 'FIND_ALL_ASSOCIATED_BADGE_SUCCESS'
export const FIND_ALL_ASSOCIATED_BADGE_FAILED = 'FIND_ALL_ASSOCIATED_BADGE_FAILED'

export const FIND_BADGE_BY_ID = 'FIND_BADGE_BY_ID'
export const FIND_BADGE_BY_ID_SUCCESS = 'FIND_BADGE_BY_ID_SUCCESS'
export const FIND_BADGE_BY_ID_FAILED = 'FIND_BADGE_BY_ID_FAILED'

export const FIND_BADGE_BY_CONDITION = 'FIND_BADGE_BY_CONDITION'
export const FIND_BADGE_BY_CONDITION_SUCCESS = 'FIND_BADGE_BY_CONDITION_SUCCESS'
export const FIND_BADGE_BY_CONDITION_FAILED = 'FIND_BADGE_BY_CONDITION_FAILED'

export const CREATE_BADGE = 'CREATE_BADGE'
export const CREATE_BADGE_SUCCESS = 'CREATE_BADGE_SUCCESS'
export const CREATE_BADGE_FAILED = 'CREATE_BADGE_FAILED'

export const UPDATE_BADGE = 'UPDATE_BADGE'
export const UPDATE_BADGE_SUCCESS = 'UPDATE_BADGE_SUCCESS'
export const UPDATE_BADGE_FAILED = 'UPDATE_BADGE_FAILED'

export const DELETE_BADGE = 'DELETE_BADGE'
export const DELETE_BADGE_SUCCESS = 'DELETE_BADGE_SUCCESS'
export const DELETE_BADGE_FAILED = 'DELETE_BADGE_FAILED'

// AUDIO
export const FIND_ALL_AUDIO = 'FIND_ALL_AUDIO'
export const FIND_ALL_AUDIO_SUCCESS = 'FIND_ALL_AUDIO_SUCCESS'
export const FIND_ALL_AUDIO_FAILED = 'FIND_ALL_AUDIO_FAILED'

export const FIND_AUDIO_BY_ID = 'FIND_AUDIO_BY_ID'
export const FIND_AUDIO_BY_ID_SUCCESS = 'FIND_AUDIO_BY_ID_SUCCESS'
export const FIND_AUDIO_BY_ID_FAILED = 'FIND_AUDIO_BY_ID_FAILED'

export const FIND_AUDIO_BY_CONDITION = 'FIND_AUDIO_BY_CONDITION'
export const FIND_AUDIO_BY_CONDITION_SUCCESS = 'FIND_AUDIO_BY_CONDITION_SUCCESS'
export const FIND_AUDIO_BY_CONDITION_FAILED = 'FIND_AUDIO_BY_CONDITION_FAILED'

export const CREATE_AUDIO = 'CREATE_AUDIO'
export const CREATE_AUDIO_SUCCESS = 'CREATE_AUDIO_SUCCESS'
export const CREATE_AUDIO_FAILED = 'CREATE_AUDIO_FAILED'

export const UPDATE_AUDIO = 'UPDATE_AUDIO'
export const UPDATE_AUDIO_SUCCESS = 'UPDATE_AUDIO_SUCCESS'
export const UPDATE_AUDIO_FAILED = 'UPDATE_AUDIO_FAILED'

export const DELETE_AUDIO = 'DELETE_AUDIO'
export const DELETE_AUDIO_SUCCESS = 'DELETE_AUDIO_SUCCESS'
export const DELETE_AUDIO_FAILED = 'DELETE_AUDIO_FAILED'

export const DELETE_MULTI_AUDIO = 'DELETE_MULTI_AUDIO'
export const DELETE_MULTI_AUDIO_SUCCESS = 'DELETE_MULTI_AUDIO_SUCCESS'
export const DELETE_MULTI_AUDIO_FAILED = 'DELETE_MULTI_AUDIO_FAILED'

export const UPLOAD_MEDIA = 'UPLOAD_MEDIA'
export const UPLOAD_MEDIA_SUCCESS = 'UPLOAD_MEDIA_SUCCESS'
export const UPLOAD_MEDIA_FAILED = 'UPLOAD_MEDIA_FAILED'

// PLAYLIST
export const FIND_ALL_PLAYLIST = 'FIND_ALL_PLAYLIST'
export const FIND_ALL_PLAYLIST_SUCCESS = 'FIND_ALL_PLAYLIST_SUCCESS'
export const FIND_ALL_PLAYLIST_FAILED = 'FIND_ALL_PLAYLIST_FAILED'

export const FIND_PLAYLIST_BY_ID = 'FIND_PLAYLIST_BY_ID'
export const FIND_PLAYLIST_BY_ID_SUCCESS = 'FIND_PLAYLIST_BY_ID_SUCCESS'
export const FIND_PLAYLIST_BY_ID_FAILED = 'FIND_PLAYLIST_BY_ID_FAILED'

export const FIND_PLAYLIST_BY_CONDITION = 'FIND_PLAYLIST_BY_CONDITION'
export const FIND_PLAYLIST_BY_CONDITION_SUCCESS = 'FIND_PLAYLIST_BY_CONDITION_SUCCESS'
export const FIND_PLAYLIST_BY_CONDITION_FAILED = 'FIND_PLAYLIST_BY_CONDITION_FAILED'

export const GET_AUDIO_LISTING = 'GET_AUDIO_LISTING'
export const GET_AUDIO_LISTING_SUCCESS = 'GET_AUDIO_LISTING_SUCCESS'
export const GET_AUDIO_LISTING_FAILED = 'GET_AUDIO_LISTING_FAILED'

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS'
export const CREATE_PLAYLIST_FAILED = 'CREATE_PLAYLIST_FAILED'

export const ADD_AUDIO_TO_PLAYLIST = 'ADD_AUDIO_TO_PLAYLIST'
export const ADD_AUDIO_TO_PLAYLIST_SUCCESS = 'ADD_AUDIO_TO_PLAYLIST_SUCCESS'
export const ADD_AUDIO_TO_PLAYLIST_FAILED = 'ADD_AUDIO_TO_PLAYLIST_FAILED'

export const DELETE_AUDIO_FROM_PLAYLIST = 'DELETE_AUDIO_FROM_PLAYLIST'
export const DELETE_AUDIO_FROM_PLAYLIST_SUCCESS = 'DELETE_AUDIO_FROM_PLAYLIST_SUCCESS'
export const DELETE_AUDIO_FROM_PLAYLIST_FAILED = 'DELETE_AUDIO_FROM_PLAYLIST_FAILED'

export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST'
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS'
export const UPDATE_PLAYLIST_FAILED = 'UPDATE_PLAYLIST_FAILED'

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS'
export const DELETE_PLAYLIST_FAILED = 'DELETE_PLAYLIST_FAILED'

export const DELETE_ON_S3 = 'DELETE_ON_S3'
export const DELETE_ON_S3_SUCCESS = 'DELETE_ON_S3_SUCCESS'
export const DELETE_ON_S3_FAILED = 'DELETE_ON_S3_FAILED'
