export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const USER_INIT = 'USER_INIT'

export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED'
export const CALL_REFRESH_TOKEN = 'CALL_REFRESH_TOKEN'

export const GET_NEW_TOKEN_SUCCESS = 'GET_NEW_TOKEN_SUCCESS'
export const GET_NEW_TOKEN_FAILED = 'GET_NEW_TOKEN_FAILED'

// BRAND
export const GET_ALL_BRAND = 'GET_ALL_BRAND'
export const GET_ALL_BRAND_SUCCESS = 'GET_ALL_BRAND_SUCCESS'
export const GET_ALL_BRAND_FAILED = 'GET_ALL_BRAND_FAILED'

export const CREATE_BRAND = 'CREATE_BRAND'
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS'
export const CREATE_BRAND_FAILED = 'CREATE_BRAND_FAILED'

export const UPDATE_BRAND = 'UPDATE_BRAND'
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS'
export const UPDATE_BRAND_FAILED = 'UPDATE_BRAND_FAILED'

export const DELETE_BRAND = 'DELETE_BRAND'
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'
export const DELETE_BRAND_FAILED = 'DELETE_BRAND_FAILED'

export const GET_BRAND_BY_ID = 'GET_BRAND_BY_ID'
export const GET_BRAND_BY_ID_SUCCESS = 'GET_BRAND_BY_ID_SUCCESS'
export const GET_BRAND_BY_ID_FAILED = 'GET_BRAND_BY_ID_FAILED'

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID'
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS'
export const GET_CATEGORY_BY_ID_FAILED = 'GET_CATEGORY_BY_ID_FAILED'

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS'
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED'

export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED'

export const GET_CATEGORY_BY_BRAND = 'GET_CATEGORY_BY_BRAND'
export const GET_CATEGORY_BY_BRAND_SUCCESS = 'GET_CATEGORY_BY_BRAND_SUCCESS'
export const GET_CATEGORY_BY_BRAND_FAILED = 'GET_CATEGORY_BY_BRAND_FAILED'

export const GET_PRODUCT_BY_CONDITION = 'GET_PRODUCT_BY_CONDITION'
export const GET_PRODUCT_BY_CONDITION_SUCCESS = 'GET_PRODUCT_BY_CONDITION_SUCCESS'
export const GET_PRODUCT_BY_CONDITION_FAILED = 'GET_PRODUCT_BY_CONDITION_FAILED'

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'
